### ISSUE TITLE
Null Reference when calling Select, Click, or SetValue with a ComboBox 

### ISSUE THREAD

**Issue by Rcallinan1** [technoscavenger/WhiteX#1]
Hi,
I recently upgraded to WhiteX after noticing the very impressive performance increase. However since the upgrade I am now unable to select any items contained in a ComboBox. 
Ex.
ComboBox resBox = SysWindow.Get<ComboBox>(ResBox);
resBox.Select(0);

Will result in:
Message: System.NullReferenceException : Object reference not set to an instance of an object.

Any help would be greatly appreciated. Thank you!

**Comment by technoscavenger** [comment]
Can you please provide a more complete code?

**Comment by technoscavenger** [comment]
Can you please check using the latest? I have implemented combobox selection.
https://github.com/technoscavenger/WhiteX/commit/0b47ef05559f717519b97a9a9de4d83ccbf0f7b7

**Comment by technoscavenger** [comment]
Fixed in 0.13.6
